# Just Test
name: test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Build container
      run: |
        docker network create data
        docker build \
        --tag inference:latest .
        docker run -d -p 8000:8000 --network data --name inference_container inference:latest

    - uses: iterative/setup-dvc@v1
    - run: |
          dvc init --no-scm -f
          
          dvc remote add origin gdrive://root
          dvc remote modify origin --local gdrive_use_service_account true

          dvc pull

      env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          
    # --build-arg GDRIVE_SERVICE_ACCOUNT_JSON="$env.GDRIVE_SERVICE_ACCOUNT_JSON" \  
    # - uses: iterative/setup-dvc@v1
    # - run: |
    #     dvc push
    # env:
    #   GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
